language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - ./travis-tool.sh bootstrap
install:
  - sh -e /etc/init.d/xvfb start
  - sudo R CMD javareconf
script: ./travis-tool.sh run_tests
notifications:
  email:
    on_success: change
    on_failure: change
env:
   global:
     - R_CHECK_ARGS="--as-cran"
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1
